### ISSUE TITLE
Dependency on unmaintained protocol-buffers

### ISSUE THREAD

**Issue by onsails** [AtnNn/haskell-rethinkdb#18]
haskell-rethinkdb is dependent on protocol-buffers which last version was released in 2012 year. It does not compile in ghc 7.8.2:

```
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/haskell-rethinkdb/.cabal-sandbox
Configuring protocol-buffers-2.0.14...
Building protocol-buffers-2.0.14...
Failed to install protocol-buffers-2.0.14
Last 10 lines of the build log ( /private/tmp/haskell-rethinkdb/.cabal-sandbox/logs/protocol-buffers-2.0.14.log ):

Text/ProtocolBuffers/WireMessage.hs:407:24: Not in scope: ‘typeOf’

Text/ProtocolBuffers/WireMessage.hs:433:77: Not in scope: ‘typeOf’

Text/ProtocolBuffers/WireMessage.hs:436:75: Not in scope: ‘typeOf’

Text/ProtocolBuffers/WireMessage.hs:440:74: Not in scope: ‘typeOf’

Text/ProtocolBuffers/WireMessage.hs:642:44: Not in scope: ‘typeOf’
cabal: Error: some packages failed to install:
protocol-buffers-2.0.14 failed during the building phase. The exception was:
ExitFailure 1
protocol-buffers-descriptor-2.0.14 depends on protocol-buffers-2.0.14 which
failed to install.
rethinkdb-1.8.0.5 depends on protocol-buffers-2.0.14 which failed to install.
```

I've already tried to contact protocol-buffers author and did not get any response.
